[session.info]
name = "Callum Clausen"
email = "callum.clausen@pg.canterbury.ac.nz"
experiment_name = "3P0-3F3_488.35nm_Lifetime"
experiment_description = "This is an example experiment to record the waveform for a lifetime measurement. Also saves the spectrometer wavelength."

[device.DPO7104_TekTronix_scope]
averages = 1000
start_bound = 1.0e-7
end_bound = 8.0e-3
area = false
waveform = true
trigger = false
samples_saved = 100000

[device.iHR550]
grating = "VIS"
step_size = 0
initial_wavelength = 732.63
final_wavelength = 732.63
bypass_homing=true
[device.iHR550.slits]
Entrance_Front = 0.2
Entrance_Side = 0.0
Exit_Front = 0.0
Exit_Side = 0.2
[device.iHR550.mirrors]
Entrance = "front"
Exit = "side"