[session.info]
name = "Callum Clausen"
email = "ccl128@uclive.ac.nz"
session_name = "Test_Scope_Driver"
session_description = "This is a test"

[device.DPO7104_TekTronix_scope]
averages = 256
start_bound = 1.0e-6
end_bound = 7.0e-6
area = true
waveform = true
trigger = false