[session]
UUID = "5823b3b2-5853-4f80-80a6-2eed769b4f70"
end_time = "2026-05-27T00:18:52.4987027Z"
start_time = "2026-05-27T00:18:39.5292776Z"

[session.info]
email = "ccl128@uclive.ac.nz"
name = "Callum Clausen"
session_description = "This is a test"
session_name = "Test_Scope_Driver"
