[session]
UUID = "e7c241b3-f913-46f4-9566-2d83b3324898"
end_time = "2026-05-27T02:03:32.1474417Z"
start_time = "2026-05-27T02:03:20.0963575Z"

[session.info]
email = "ccl128@uclive.ac.nz"
name = "Callum Clausen"
session_description = "This is a test"
session_name = "Test_Scope_Driver"
